// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: R2D2_Monitor

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_PanelScreenBorder;
extern lv_obj_t * ui_LabelTitle1;
extern lv_obj_t * ui_LabelTitle2;
extern lv_obj_t * ui_IPadd;
extern lv_obj_t * ui_Spinner;
extern lv_obj_t * ui_sec;
extern lv_obj_t * ui_ImageR2D2;
extern lv_obj_t * ui_LabelRSSI;
extern lv_obj_t * ui_PanelWiFiQuality;
extern lv_obj_t * ui_RSSI;
extern lv_obj_t * ui_LabelUpdating;
extern lv_obj_t * ui_LabelHexTime;
extern lv_obj_t * ui_R2D2LED;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_LabelPercent1;
extern lv_obj_t * ui_PanelLine1;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_PanelLine2;
extern lv_obj_t * ui_LabelFPS;
extern lv_obj_t * ui_FPS;
extern lv_obj_t * ui_PanelHumidity;
extern lv_obj_t * ui_LabelHumidity;
extern lv_obj_t * ui_LabelPercent;
extern lv_obj_t * ui_PanelLine3;
extern lv_obj_t * ui_Humidity;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

