// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: R2D2_Monitor

#include "ui.h"

lv_obj_t * ui_MainScreen;
lv_obj_t * ui_PanelScreenBorder;
lv_obj_t * ui_LabelTitle1;
lv_obj_t * ui_LabelTitle2;
lv_obj_t * ui_IPadd;
lv_obj_t * ui_Spinner;
lv_obj_t * ui_sec;
lv_obj_t * ui_ImageR2D2;
lv_obj_t * ui_LabelRSSI;
lv_obj_t * ui_PanelWiFiQuality;
lv_obj_t * ui_RSSI;
lv_obj_t * ui_LabelUpdating;
lv_obj_t * ui_LabelHexTime;
lv_obj_t * ui_R2D2LED;
lv_obj_t * ui_LabelTemp;
lv_obj_t * ui_LabelPercent1;
lv_obj_t * ui_PanelLine1;
lv_obj_t * ui_Temp;
lv_obj_t * ui_PanelLine2;
lv_obj_t * ui_LabelFPS;
lv_obj_t * ui_FPS;
lv_obj_t * ui_PanelHumidity;
lv_obj_t * ui_LabelHumidity;
lv_obj_t * ui_LabelPercent;
lv_obj_t * ui_PanelLine3;
lv_obj_t * ui_Humidity;

// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScreenBorder = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelScreenBorder, 176);
    lv_obj_set_height(ui_PanelScreenBorder, 324);
    lv_obj_set_align(ui_PanelScreenBorder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelScreenBorder, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelScreenBorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelScreenBorder, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelScreenBorder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScreenBorder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScreenBorder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScreenBorder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle1, -42);
    lv_obj_set_y(ui_LabelTitle1, -142);
    lv_obj_set_align(ui_LabelTitle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTitle1, "R2D2");
    lv_obj_set_style_text_font(ui_LabelTitle1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle2, -33);
    lv_obj_set_y(ui_LabelTitle2, -119);
    lv_obj_set_align(ui_LabelTitle2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTitle2, "MONITOR");
    lv_obj_set_style_text_color(ui_LabelTitle2, lv_color_hex(0x4F4E60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPadd = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_IPadd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPadd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPadd, 10);
    lv_obj_set_y(ui_IPadd, 52);
    lv_label_set_text(ui_IPadd, "192.168.254.254");
    lv_obj_set_style_text_color(ui_IPadd, lv_color_hex(0x3535C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPadd, 250, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner = lv_spinner_create(ui_MainScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner, 40);
    lv_obj_set_height(ui_Spinner, 40);
    lv_obj_set_x(ui_Spinner, 57);
    lv_obj_set_y(ui_Spinner, -133);
    lv_obj_set_align(ui_Spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0x3535C6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_sec = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec, 57);
    lv_obj_set_y(ui_sec, -133);
    lv_obj_set_align(ui_sec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sec, "59");
    lv_obj_set_style_text_font(ui_sec, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageR2D2 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ImageR2D2, &ui_img_r2d2_png);
    lv_obj_set_width(ui_ImageR2D2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageR2D2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageR2D2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageR2D2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageR2D2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelRSSI = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelRSSI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRSSI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRSSI, 49);
    lv_obj_set_y(ui_LabelRSSI, -106);
    lv_obj_set_align(ui_LabelRSSI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRSSI, "RSSI :");
    lv_obj_set_style_text_font(ui_LabelRSSI, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWiFiQuality = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelWiFiQuality, 8);
    lv_obj_set_height(ui_PanelWiFiQuality, 8);
    lv_obj_set_x(ui_PanelWiFiQuality, 73);
    lv_obj_set_y(ui_PanelWiFiQuality, -105);
    lv_obj_set_align(ui_PanelWiFiQuality, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWiFiQuality, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWiFiQuality, lv_color_hex(0x12C210), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWiFiQuality, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWiFiQuality, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSI = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSI, -8);
    lv_obj_set_y(ui_RSSI, 59);
    lv_obj_set_align(ui_RSSI, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_RSSI, "-99dBm");
    lv_obj_set_style_text_font(ui_RSSI, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUpdating = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelUpdating, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUpdating, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUpdating, 54);
    lv_obj_set_y(ui_LabelUpdating, -78);
    lv_obj_set_align(ui_LabelUpdating, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUpdating, "updating\n....");
    lv_obj_set_style_text_color(ui_LabelUpdating, lv_color_hex(0x616161), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUpdating, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUpdating, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHexTime = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelHexTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHexTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHexTime, -8);
    lv_obj_set_y(ui_LabelHexTime, 83);
    lv_obj_set_align(ui_LabelHexTime, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelHexTime, "0x258");
    lv_obj_set_style_text_color(ui_LabelHexTime, lv_color_hex(0x616161), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHexTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHexTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_R2D2LED = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_R2D2LED, 7);
    lv_obj_set_height(ui_R2D2LED, 7);
    lv_obj_set_x(ui_R2D2LED, -15);
    lv_obj_set_y(ui_R2D2LED, -57);
    lv_obj_set_align(ui_R2D2LED, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_R2D2LED, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_R2D2LED, lv_color_hex(0x12C210), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_R2D2LED, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_R2D2LED, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -54);
    lv_obj_set_y(ui_LabelTemp, 98);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "TEMP");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0x4F4E60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPercent1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelPercent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPercent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPercent1, -1);
    lv_obj_set_y(ui_LabelPercent1, 117);
    lv_obj_set_align(ui_LabelPercent1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPercent1, "C");
    lv_obj_set_style_text_color(ui_LabelPercent1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPercent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPercent1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLine1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelLine1, 70);
    lv_obj_set_height(ui_PanelLine1, 3);
    lv_obj_set_x(ui_PanelLine1, -40);
    lv_obj_set_y(ui_PanelLine1, 108);
    lv_obj_set_align(ui_PanelLine1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLine1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temp = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp, 11);
    lv_obj_set_y(ui_Temp, 269);
    lv_label_set_text(ui_Temp, "33.33");
    lv_obj_set_style_text_font(ui_Temp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLine2 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelLine2, 70);
    lv_obj_set_height(ui_PanelLine2, 3);
    lv_obj_set_x(ui_PanelLine2, -40);
    lv_obj_set_y(ui_PanelLine2, 139);
    lv_obj_set_align(ui_PanelLine2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLine2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelFPS = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelFPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFPS, -64);
    lv_obj_set_y(ui_LabelFPS, 148);
    lv_obj_set_align(ui_LabelFPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFPS, "FPS : ");
    lv_obj_set_style_text_font(ui_LabelFPS, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FPS = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_FPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FPS, -124);
    lv_obj_set_y(ui_FPS, 303);
    lv_obj_set_align(ui_FPS, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_FPS, "999");
    lv_obj_set_style_text_font(ui_FPS, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHumidity = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelHumidity, 64);
    lv_obj_set_height(ui_PanelHumidity, 45);
    lv_obj_set_x(ui_PanelHumidity, 45);
    lv_obj_set_y(ui_PanelHumidity, 129);
    lv_obj_set_align(ui_PanelHumidity, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelHumidity, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHumidity, lv_color_hex(0x3535C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHumidity, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHumidity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidity = lv_label_create(ui_PanelHumidity);
    lv_obj_set_width(ui_LabelHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumidity, -8);
    lv_obj_set_y(ui_LabelHumidity, -11);
    lv_obj_set_align(ui_LabelHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidity, "HUM");
    lv_obj_set_style_text_color(ui_LabelHumidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumidity, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPercent = lv_label_create(ui_PanelHumidity);
    lv_obj_set_width(ui_LabelPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPercent, 19);
    lv_obj_set_y(ui_LabelPercent, -11);
    lv_obj_set_align(ui_LabelPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPercent, "%");
    lv_obj_set_style_text_color(ui_LabelPercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPercent, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLine3 = lv_obj_create(ui_PanelHumidity);
    lv_obj_set_width(ui_PanelLine3, 53);
    lv_obj_set_height(ui_PanelLine3, 3);
    lv_obj_set_align(ui_PanelLine3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLine3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLine3, lv_color_hex(0x0B0B38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLine3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLine3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_PanelHumidity);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, 0);
    lv_obj_set_y(ui_Humidity, 12);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity, "99");
    lv_obj_set_style_text_color(ui_Humidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_PanelScreenBorder = NULL;
    ui_LabelTitle1 = NULL;
    ui_LabelTitle2 = NULL;
    ui_IPadd = NULL;
    ui_Spinner = NULL;
    ui_sec = NULL;
    ui_ImageR2D2 = NULL;
    ui_LabelRSSI = NULL;
    ui_PanelWiFiQuality = NULL;
    ui_RSSI = NULL;
    ui_LabelUpdating = NULL;
    ui_LabelHexTime = NULL;
    ui_R2D2LED = NULL;
    ui_LabelTemp = NULL;
    ui_LabelPercent1 = NULL;
    ui_PanelLine1 = NULL;
    ui_Temp = NULL;
    ui_PanelLine2 = NULL;
    ui_LabelFPS = NULL;
    ui_FPS = NULL;
    ui_PanelHumidity = NULL;
    ui_LabelHumidity = NULL;
    ui_LabelPercent = NULL;
    ui_PanelLine3 = NULL;
    ui_Humidity = NULL;

}
